const GRADE_EMOJI = { A: '\u2705', B: '\ud83d\udfe2', C: '\u26a0\ufe0f', D: '\ud83d\udfe0', F: '\ud83d\udd34' };
const SEVERITY_ORDER = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];

const DEFAULT_SECTIONS = {
  scores: true,
  repoHealth: true,
  findings: true,
  alternatives: true,
  verdict: true,
};

function generateReport(analysis, sections) {
  const opts = { ...DEFAULT_SECTIONS, ...sections };

  const {
    packageName = 'unknown',
    grade = '?',
    weightedScore = 0,
    scores = {},
    gradeRationale = '',
    findings = [],
    alternatives = [],
    verdict = '',
    repoHealth = null,
    timestamp = new Date().toISOString(),
    input = '',
  } = analysis;

  const emoji = GRADE_EMOJI[grade] || '';
  const lines = [];

  // Header (always included)
  lines.push(`# DepScope Report: ${packageName}`);
  lines.push('');
  lines.push(`> ${emoji} **Grade: ${grade}** | Score: ${weightedScore}/100 | ${new Date(timestamp).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Score breakdown
  if (opts.scores) {
    lines.push('## Score Breakdown');
    lines.push('');
    lines.push('| Dimension | Score | Weight |');
    lines.push('|-----------|-------|--------|');
    const dims = [
      ['Security', scores.security, '30%'],
      ['Maintenance', scores.maintenance, '25%'],
      ['Stability', scores.stability, '20%'],
      ['Community', scores.community, '15%'],
      ['Documentation', scores.documentation, '10%'],
    ];
    for (const [name, score, weight] of dims) {
      lines.push(`| ${name} | ${score != null ? score : 'N/A'}/100 | ${weight} |`);
    }
    lines.push(`| **Overall** | **${weightedScore}/100** | |`);
    lines.push('');

    if (gradeRationale) {
      lines.push(`**${gradeRationale}**`);
      lines.push('');
    }
  }

  // Repo health summary
  if (opts.repoHealth && repoHealth) {
    lines.push('## Repository Health');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push('|--------|-------|');
    if (repoHealth.stars != null) lines.push(`| Stars | ${repoHealth.stars.toLocaleString()} |`);
    if (repoHealth.forks != null) lines.push(`| Forks | ${repoHealth.forks.toLocaleString()} |`);
    if (repoHealth.license) lines.push(`| License | ${repoHealth.license} |`);
    if (repoHealth.lastCommitDaysAgo != null) lines.push(`| Last Commit | ${repoHealth.lastCommitDaysAgo} days ago |`);
    if (repoHealth.contributorCount != null) lines.push(`| Contributors | ${repoHealth.contributorCount} |`);
    if (repoHealth.busFactorScore) lines.push(`| Bus Factor | ${repoHealth.busFactorScore} |`);
    if (repoHealth.commitFrequencyPerWeek != null) lines.push(`| Commits/Week | ${repoHealth.commitFrequencyPerWeek} |`);
    if (repoHealth.openIssues != null) lines.push(`| Open Issues | ${repoHealth.openIssues} |`);
    lines.push('');
  }

  if (opts.scores || (opts.repoHealth && repoHealth)) {
    lines.push('---');
    lines.push('');
  }

  // Findings grouped by severity
  if (opts.findings && findings.length > 0) {
    lines.push('## Findings');
    lines.push('');
    for (const severity of SEVERITY_ORDER) {
      const group = findings.filter(f => f.severity === severity);
      if (group.length === 0) continue;
      lines.push(`### ${severity}`);
      lines.push('');
      for (const f of group) {
        lines.push(`- **${f.title}** \u2014 ${f.detail}`);
        if (f.recommendation) {
          lines.push(`  - *Recommendation:* ${f.recommendation}`);
        }
      }
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  }

  // Alternatives
  if (opts.alternatives && alternatives.length > 0) {
    lines.push('## Alternatives');
    lines.push('');
    lines.push('| Package | Migration Difficulty | Why |');
    lines.push('|---------|---------------------|-----|');
    for (const alt of alternatives) {
      lines.push(`| ${alt.name || 'N/A'} | ${alt.migrationDifficulty || 'N/A'} | ${alt.reason || ''} |`);
    }
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Verdict
  if (opts.verdict && verdict) {
    lines.push('## Verdict');
    lines.push('');
    lines.push(`> ${verdict}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  // Footer (always included)
  const sourceUrl = input && input.includes('github.com') ? ` | [Source](${input})` : '';
  lines.push(`<sub>Generated by [DepScope](https://github.com/Eman-Gon/depscope) on ${new Date(timestamp).toISOString()}${sourceUrl} | Grade thresholds: A \u2265 80, B \u2265 65, C \u2265 50, D \u2265 35, F < 35</sub>`);
  lines.push('');

  return lines.join('\n');
}

module.exports = { generateReport };
